### ISSUE TITLE
Getting "The following resource types are not supported for resource import: AWS::CloudWatch::Dashboard,AWS::Lambda::Permission" error while trying to use this stack

### ISSUE THREAD

**Issue by eranyo** [aws-samples/amazon-ec2-global-dashboard#3]
Hi 

I used this CloudFormation in the past and it worked perfectly.
I tried to use it again today in another account and i'm getting the next error after uploading the template : **_The following resource types are not supported for resource import: AWS::CloudWatch::Dashboard,AWS::Lambda::Permission_**

Its seems that AWS::CloudWatch::Dashboard,AWS::Lambda::Permission are no longer supported by CloudFormation.
Someone can advice which resource I can use instead, because this dashboard is very useful  ? 

Thanks,
Eran.

**Comment by xonor** [comment]
Hey Eran,

Thank you for reaching and sorry to hear about the issue you are having.

It appears that you are trying to use the Import feature in CloudFormation to launch the stack.
The Import feature does not support some of the essential resources of the **Amazon EC2 Global Dashboard**.

Can you please try again to launch the stack but choose 'standard' instead of 'import resources'.
![Screen Shot 2020-10-07 at 4 29 48 PM](https://user-images.githubusercontent.com/9273913/95354121-f9ee9080-08bb-11eb-8ca8-d6fb946a58e5.png)

Resources that support import and drift detection operations:
-- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

I'm delighted to hear that you think the dashboard is useful.
Hoping to push some new features soon which you might find even more useful.

If you have any further questions or concerns, please let me know and I'll gladly help.

Kind regards,
Conor

**Comment by eranyo** [comment]
Hey Conor,

Thanks for your reply. I tried it again with the Standard option and it passed successfully.
I don't know why i selected the import option .... :-) 

This dashboard is very useful and i'll be to see new features.

BR,
Eran.

**Comment by amolksagar** [comment]
Hi @xonor,

I have a genuine case of Stack import where my CFN stack is drifted. The stack seems to be lagging behind the AWS resources in terms of some resource properties i.e. The actual AWS Resources have correct properties and CFN stack has incorrect properties

Steps I have taken so far 2 drifted resources of type AWS::ECS::TaskDefinition and  AWS::ECS::Service:
1. Updated the DeletionPolicy and UpdateReplacePolicy to 'Retain' and deployed the stack
2. Commented the code for AWS::ECS::TaskDefinition and  AWS::ECS::Service in the template and deployed the stack again
3. **Problematic step**: Selected 'Import resources into stack' and selected the updated template which has resources of type AWS::ECS::TaskDefinition and  AWS::ECS::Service redefined. I am getting an error 'The following resource types are not supported for resource import: AWS::EC2::SecurityGroupIngress,AWS::ElasticLoadBalancingV2::ListenerRule' . If you notice I am not even trying to import  SecurityGroupIngress and ListenerRule but it still complains about it.

What can be done in this case? Can I try to UPDATE the stack straight away with the new values instead of using the 'Import into stack'?
